# Common vars
availability_zone: melbourne-qh2-uom

# Volume 
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 80
  - vol_name: demo-vol-1-2
    vol_size: 10
  - vol_name: demo-vol-2-1
    vol_size: 80
  - vol_name: demo-vol-2-2
    vol_size: 10
  - vol_name: demo-vol-3-1
    vol_size: 80
  - vol_name: demo-vol-3-2
    vol_size: 10
  - vol_name: demo-vol-4-1
    vol_size: 80
  - vol_name: demo-vol-4-2
    vol_size: 10

# Security group
# Security group
security_groups:
  - name: administration
    description: "Security group for server administration and remote access (e.g. access via SSH or HTTP for Frontend)"
  - name: intra_cluster_communication
    description: "Security group for communication between CouchDB nodes in cluster"

security_group_rules_public: 
  - name: administration
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_private: 
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: intra_cluster_communication


# Instance
instances:
  - name: instance1
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
  - name: instance2
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']
  - name: instance3
    volumes: ['demo-vol-3-1', 'demo-vol-3-2']
  - name: instance4
    volumes: ['demo-vol-4-1', 'demo-vol-4-2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: cloud
instance_flavor1: uom.mse.2c9g
instance_flavor2: uom.mse.1c4g

